#!/bin/bash
TITLE="EXTSEARCH"
OVERVIEW="Recursively Searches a Directory for a Specified Extension"
USAGE="extsearch extension(mandatory) dir(optional)"
source /usr/local/share/geoffhelp
EXT=$1
if [ -z $1 ]
then
	extsearch help
	exit
fi
if [ -z $2 ]
then
	find ./ -regex ".*$EXT$"
else
DIR=$2
	find $DIR -regex ".*$EXT$"
fi
