#!/bin/bash
ISLANDDIR="/usr/local/tomcat/webapps/ShopV4/store/"
ISLANDS=`ls $ISLANDDIR`
if [ $1 == 'list' ]
then
        echo $ISLANDS
        exit
fi

#cat $ISLANDDIR$1/$CHECKFILE | grep version | grep -v require | cut -d \" -f 4 
for i in `ls $ISLANDDIR$1/ | grep .php`
do
echo -ne "$i is version " && cat $ISLANDDIR$1/$i | grep version | grep -v require | cut -d \" -f 4
done
